version: "3"
volumes:
  data:
services:
  app:
    build: .
    # image: figassis/mysql-backup:0.0.3
    restart: always
    container_name: backup
    volumes:
      - data:/tmp/data
      - ./config.yaml:/etc/mysql-backup/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"